if(instance_exists(_inst)){
	if(_delay==0){
		_time+=1;
		if(_time>=_duration){
			variable_instance_set(_inst,_var_name,_start+_change);
			instance_destroy();
		}else{
			event_user(0);
		}
	}else{
		_delay-=1;
	}
}else{
	instance_destroy();
}